### ISSUE TITLE
Get JSON data back from percy build:wait

### ISSUE THREAD

**Issue by sandstrom** [percy/cli#1268]
## Summary

We don't want to use the Percy Github integration, due to security concerns. When you get hacked, as most companies eventually are (Solarwinds and Heroku are two recent examples), we don't want all our source code to leak.

`percy build:wait --build 123` should have a `--json` flag that returns json data that looks like this:

```json
{ "status" : "changes", "change_count" : 8, "build_url" : "https://percy.io/…builds/27676" }
```

## Problem

For security, we'd like to use the Percy CLI, which we can pin with npm and checksums (fairly secure). Your current CLI is great and gets us most of the way.

We'll run something like this in Github Actions:

~~~
percy exec -- node percy-test.js 
[percy] Percy has started!
[percy] Running "node percy-test.js"
[percy] Snapshot taken: Website
[percy] Finalized build #4: https://percy.io/57827…/website/builds/27676
~~~

After trigger the build, I need to wait for it to complete, before we can report back in the Github Action check (CI flow).

Do do that, you have the build:wait command. Great! When running `percy build:wait --build XXX` I get relevant data back.

But it's just text, so not easy to parse.

~~~
$ percy build:wait --build 27676
[percy] Build #3 finished! https://percy.io/57827…/website/builds/27676
[percy] Found 8 changes

~~~

Would be great with a `--json` option, that we can parse programmatically.

Because we need to manually grab the URL and the status. Otherwise we cannot update the PR properly (because we're not using your Github integration, for security reasons we talked about).

Ideally we'd get something like this:

~~~
$ percy build:wait --build 27676 --json
{ "status" : "changes", "change_count" : 8, "build_url" : "https://percy.io/…builds/27676" }

# Response with no changes
{ "status" : "no_changes", "build_url" : "https://percy.io/…builds/27676" }

# Failure
{ "status" : "failed", "build_url" : "https://percy.io/…builds/27676" }
~~~

Maybe you'll want to give the keys other names, obviously. But you get the idea.

This would be enough for us to then call the Github API and add a comment to the PR, so basically we'd have the same flow as with a Github integration, but without any of the security concerns.

## Pull-request linking

On [this page](https://docs.percy.io/docs/environment-variables) you have details about the ENV variable `PERCY_PULL_REQUEST` ("The pull request number to associate to the build, if any"). 

But how would you know the base path? I'm thinking you'd rather want it to be something like `PERCY_PULL_REQUEST_URL` where we enter the full URL to the PR. That way, you can link to that PR from within your UI, without actually having read access to it (it's just a link).

Or, you'd need to let us set the repo base path in your settings. We'd set it to e.g. `https://github.com/my-org/my-repo`.

**Comment by itsjwala** [comment]
* hey @sandstrom you could use `@percy/client` and check our [API reference](https://docs.percy.io/reference) 
> But how would you know the base path?

For this, we rely on GitHub integration to query the pull request details.

Since this is not a CLI issue, I'm closing this task, Please feel free to reach out to us via https://browserstack.com/support

**Comment by sandstrom** [comment]
@itsjwala Thanks for taking time to look at it.

I'd argue it is related to the CLI though, because for us to setup an integration via Github Actions, without using your Github integration (we cannot use it for security reasons), we need to use the CLI.

And the CLI output isn't machine readable, so what I'm proposing is basically to just add a flag and offer the output as machine-readable JSON.

It's not a bug though! So if you'd rather track this as a suggestion, feel free to keep this issue closed.

**Comment by sandstrom** [comment]
Friendly ping @ninadbstack @shantanuk-browserstack 😄 

For security reasons, we cannot use the Github Apps integration, because your app requires full source-code access. There has been [hacks of third-party software such as Heroku](https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/), that has given attackers access to Github source code.

However, good news is that you have an awesome CLI, that we can run in our Github runner. That way, we don't need to give you access to source-code.

It's working really well overall! 🎉 

But there are a few minor problems that I'd like to tell you about:

- `percy build:wait --build 27676` emits text, but a `--json` flag would make integration into Github Actions much easier
- The env variable `PERCY_PULL_REQUEST` should have a sibling `PERCY_PULL_REQUEST_URL`. That way, you can link to the PR from your UI, without actually having access to the PR data. Or you could let us set the repo base path in your settings, e.g. `https://github.com/my-org/my-repo`.

Is this something you would consider improving?

I think as a provider, it's in your interest to offer integration mechanisms where access rights are limited (principle of least privilege), and you're already offering stuff that gets us 95% of the way there. Just a few more minor adjustments and we could integrate all of Percy in a security-friendly manner.

**Comment by itsjwala** [comment]
@sandstrom 

> percy build:wait --build 27676 emits text, but a --json flag would make integration into Github Actions much easier

You can create a separate enhancement issue here for this, though we'd like it if you could give us PR for this.



A workaround would be using `@percy/client` This would require you to create a node script file (and maybe commit in your VCS), check this readme on how to use client package - [ref](https://github.com/percy/cli/blob/master/packages/client/README.md#wait-for-a-build-to-be-finished)



> The env variable PERCY_PULL_REQUEST should have a sibling PERCY_PULL_REQUEST_URL. That way, you can link to the PR from your UI, without actually having access to the PR data. Or you could let us set the repo base path in your settings, e.g. https://github.com/my-org/my-repo.

Thanks for your valuable suggestion, you can raise a feature request to us by reaching out to our support linked previously, Though, no ETA is promised as we're working on current deliveries.

**Comment by sandstrom** [comment]
@itsjwala Thanks!

I'll look at what you suggest.
