### ISSUE TITLE
Unable to use @percy/storybook with `--parallel` flag

### ISSUE THREAD

**Issue by elliotwestlake** [percy/cli#1294]
## The problem

You are unable to set `--parallel` when using `percy storybook ./storybook-static`

## Environment

- Node version: 18.16.1
- `@percy/cli` version: 1.20.0
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID:
- OS version:
- Type of shell command-line [interface]:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Debug logs

If you are reporting a bug, _always_ include logs! [Give the "Debugging SDKs"
document a quick read for how to gather logs](https://docs.percy.io/docs/debugging-sdks#debugging-sdks)

Please do not trim or edit these logs, often times there are hints in the full
logs that help debug what is going on.

## Code to reproduce issue

Given the nature of testing/environment bugs, it’s best to try and isolate the
issue in a reproducible repo. This will make it much easier for us to diagnose
and fix.

Run the following:
```bash
pnpm percy storybook --parallel ./storybook-static
```

**Comment by itsjwala** [comment]
hey @elliotwestlake 👋 

* `@percy/storybook` would be correct repo to raise this.
* There is no flag like `--parallel` for `storybook` command, you'll have to use `--shard-size` e.t.c 
  * Please checkout this doc https://docs.percy.io/docs/storybook#running-in-parallel for clarity.
* If you still have further queries, please reach out to us through [support](https://www.browserstack.com/contact?ref=percy)
