### ISSUE TITLE
Outdated docs for static snapshot options

### ISSUE THREAD

**Issue by finn-wa** [percy/cli#1319]
The documentation [here](https://github.com/percy/cli/blob/master/packages/cli-snapshot/README.md#static-options) references an `overrides` property that no longer exists. I believe it has been replaced by the `options` property (which is not described in the docs).

**Comment by ninadbstack** [comment]
Hey @finn-wa! Thanks for reporting this, we will fix docs right away! 

As per https://github.com/percy/cli/pull/819 overrides were replaced by options 

Fixing this in https://github.com/percy/cli/pull/1322

**Comment by ninadbstack** [comment]
Fixed and closing. this will update on `npmjs` in next release
