### ISSUE TITLE
Fonts arent showing up in percy snapshots

### ISSUE THREAD

**Issue by ryan-case-ml** [percy/cli#1332]
## The problem

We have a UI component library that we have built internal to our organization. This library is used in our project for various reuseable components that adhere to our design system specs. Typography components are just some of those that we use. These components use fonts that are not hosted anywhere, they are simply local assets to the component library. When we try to use percy to generate snapshots, these fonts do not appear to be included in the assets captured by percy. When turning off headless mode, I can see that the fonts are loading in the browser that percy is opening to capture assets, but then they don't show up in the generated snapshots.

## Environment

- Node version:
- `@percy/cli` version: 1.26.2
- Version of Percy SDK you’re using: @percy/playwright v1.0.4
- If needed, a build or snapshot ID: 29364905

## Details

I've tried increasing the network timeout to 750 ms, still no luck. I've tried bringing in the fonts from our component library as local assets to the project and setting them up as font faces in our global css. I've tried setting the font faces up in percy specific css. Nothing seems to be working.

**Comment by itsjwala** [comment]
Hello @ryan-case-ml 👋 

Please reach out to us via our support, we'll be happy to assist further.
