### ISSUE TITLE
Please allow longer network idle timeouts

### ISSUE THREAD

**Issue by jimCresswell** [percy/cli#1425]
Hi,

We're seeing some issues with Percy timing out on slow asset requests, partly when loading embedded assets from third parties where we have no control over the request efficiency. The assets are important to the page visuals and functionality so I can't ignore them. I'd like to increase the maximum network idle timeout from 750ms to 2000ms.

Thanks,
Jim

**Comment by itsjwala** [comment]
we provide a undocumented environment variable - `PERCY_NETWORK_IDLE_WAIT_TIMEOUT`  please try it out with latest CLI.

**Comment by jimCresswell** [comment]
thanks @itsjwala, I'll give that a go next week
