### ISSUE TITLE
Base64 encoded SVGs cause error when capturing

### ISSUE THREAD

**Issue by ajoneil** [percy/cli#1586]
## The problem

We have a base64 encoded SVG image on our page, and our tests work when Percy snapshots are not enabled. When enabling them, there is an HTTP request for the serialised image which fails:
```
     Failure/Error: raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
     
     ActionController::RoutingError:
       No route matches [GET] "/__serialized__/_51p3niala.svg+xml"
```

## Environment

- Node version: v18.19.0 LTS
- `@percy/cli` version: 1.28.5
- Version of Percy SDK you’re using: percy-capybara
- OS version: Debian Bookworm based Docker image (official ruby docker image)
- Type of shell command-line [interface]: bash

## Details

This error only occurs when we upgrade our Percy CLI from 1.27.4 to the latest 1.28.5. Much like #1568, https://github.com/percy/cli/commit/0a48e87d5b5cfaf1d469728e3d6de34171edfe2a appears to be the culprit. 

Unfortunately the fix for that issue (#1571) does not work as our Capybara drives Selenium in a different docker image, and so our host is not `127.0.0.1` or `localhost` but a `192.168.` address.

**Comment by shantanuk-browserstack** [comment]
Hi @ajoneil , 

Thank you for bringing this to our attention. Rest assured, we are currently investigating this.

**Comment by Yama-Tomo** [comment]
Same issue. I think [this rewrite](https://github.com/percy/cli/blob/4a6368c869ff961e0d958512e98913e4418884b1/packages/dom/src/utils.js#L44-L46) needs to be configurable.

**Comment by Yama-Tomo** [comment]
@shantanuk-browserstack any update?
