### ISSUE TITLE
[percy:cli] Error: Finalizing build # failed: cannot finalize before all snapshot resources are uploaded.

### ISSUE THREAD

**Issue by unlikelyzero** [percy/cli#1716]
## The problem

Build is failing due to a timing issue in percy cli https://github.com/nasa/openmct/issues/7829

## Environment

    "@percy/cli": "1.27.4",
    "@percy/playwright": "1.0.4",

## Details

It looks like a failed network response from the percy server.

## Debug logs

[percy:core:browser] Closing browser (783ms)
[percy:core:browser] Browser closed (23ms)
[percy:client] Finalizing build 36306715... (0ms)
[percy:cli] Error: Finalizing build 36306715 failed: cannot finalize before all snapshot resources are uploaded. This is likely a client error, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize.
    at handleFinished (file:///root/project/e2e/node_modules/@percy/client/dist/utils.js:186:17)
    at IncomingMessage.<anonymous> (file:///root/project/e2e/node_modules/@percy/client/dist/utils.js:202:27)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) (182ms)

## Code to reproduce issue

Everything we do is open source and can be seen here https://app.circleci.com/pipelines/github/nasa/openmct/23591/workflows/88c419fb-2dcf-4f80-a3cf-4a6217042330/jobs/103331

**Comment by prklm10** [comment]
@unlikelyzero we are checking this. Thanks for raising the issue.

**Comment by prklm10** [comment]
@unlikelyzero can you try few things -> 
- Please update the percy cli version to the latest.
- Can you add concurrency: 2 in you percy.yml file  [docs ](https://www.browserstack.com/docs/percy/take-percy-snapshots/overview)
- Can you try above stuff and revert back to us if you are seeing this issue is still persistent or not.

**Comment by ninadbstack** [comment]
Closing as stale.
