### ISSUE TITLE
Shadow DOM no longer serialized in Chrome 131 (or in Chrome 130 in combination with Percy 1.30.4)

### ISSUE THREAD

**Issue by mixonic** [percy/cli#1819]
On a private codebase, we no longer see shadow DOM serialized into HTML for upload to Percy.

* After adding Chrome 131 to our test suite, these elements never serialized.
* After upgrading to Percy CLI `1.30.2`-> `1.30.4` (in hopes it would address the issue), shadow DOM no longer serializes in Chrome 130 or 131.

The shadow root for our Web Components is open.

We're attempting to create a reproduction of this to support debugging, but wanted to open this ticket in case there are others in the Percy user community experiencing this issue.

However we can provide example before/after serialized HTML fragments:

Before:

```html
<custom-toggle data-test-show-title-toggle="" class="mb-2.5 hydrated" checked="" data-percy-shadow-host="" data-percy-element-id="_fa3164h6n"><template shadowrootmode="open"><link rel="stylesheet" data-percy-adopted-stylesheets-serialized="true" href="https://HOSTNAME_REDACTED/__serialized__/_8oa38x04m.css"><label class="wrapper"><button class="toggle focus-visible:custom-form-el-focus toggled" aria-pressed="true" aria-labelledby="label"></button><span id="label" class="label-text"><slot name="label"></slot></span></label></template></custom-toggle>
```

After Chrome 131 (or Percy `1.30.4` and Chrome 130):

```html
<custom-toggle data-test-show-title-toggle="" class="mb-2.5 hydrated" checked="" data-percy-shadow-host="" data-percy-element-id="_9zvgm69j8"></custom-toggle>
```

**Comment by pankaj443** [comment]
Hey @mixonic thanks for reporting, we will be checking this. Please share a minimum reproducible unserialized HTML sample. Would be helpful in debugging.

**Comment by pankaj443** [comment]
Hey @mixonic we have release CLI v1.30.5-beta.2 with fix for the issue. Please check

**Comment by eliasdawson-addepar** [comment]
Thanks @pankaj443 I can confirm on behalf of @mixonic that `v1.30.5-beta.2` fixes the issue.

**Comment by pankaj443** [comment]
Thanks, closing the issue as its resolved now.
