### ISSUE TITLE
Does not work with Yarn 2 (Berry)

### ISSUE THREAD

**Issue by AaronBuxbaum** [percy/cli#295]
When trying to use `percy exec` with Yarn 2, the following is thrown:
```
[MODULE_NOT_FOUND] Error Plugin: @percy/cli: Qualified path resolution failed - none of the candidates can be found on the disk.
```

this is likely because you can't necessarily make the assumption that repos will be available, for example: `node_modules/@percy/cli-exec/dist/hooks/init` won't be correct because they're not under a `node_modules` folder. However, even with this, you could theoretically install each plugin and `yarn unplug` it.

I think a biggest problem comes because it can't seem to find the `index.js` file when pointed at a folder:
```
Source path: /Users/aaron/Work/web/node_modules/@percy/cli-exec/dist/commands/exec
    Rejected candidate: 
    /Users/aaron/Work/web/node_modules/@percy/cli-exec/dist/commands/exec
    Rejected candidate: 
    /Users/aaron/Work/web/node_modules/@percy/cli-exec/dist/commands/exec.js
    Rejected candidate: 
    /Users/aaron/Work/web/node_modules/@percy/cli-exec/dist/commands/exec.json
    Rejected candidate: 
    /Users/aaron/Work/web/node_modules/@percy/cli-exec/dist/commands/exec.node
```

Any suggestions here?

**Comment by Robdel12** [comment]
Hey @AaronBuxbaum! Are you using Yarn 2s Plug n Play?

**Comment by AaronBuxbaum** [comment]
> Hey @AaronBuxbaum! Are you using Yarn 2s Plug n Play? 

Yup. Currently in loose mode, though hopefully eventually in strict mode

**Comment by Robdel12** [comment]
Gotcha! Unless the changes are minimal, I don't think it's something we'll adopt.

**Comment by wwilsman** [comment]
I wanted to add that we depend on OCLIF, which itself does not yet support PnP: https://github.com/oclif/config/pull/171

**Comment by AaronBuxbaum** [comment]
> Perhaps you may have some luck with [Yarn's pnpify](https://yarnpkg.com/advanced/pnpify)?

this would be fine, but this is actually what I'm doing above. If I don't use pnpify, I get an error about being unable to find `package.json` files

**Comment by AaronBuxbaum** [comment]
While we're waiting for oclif/config, I've done the following:
1. Submitted a ping on the PR: https://github.com/oclif/config/pull/171
2. Set the package in `package.json` under `resolutions`: `"@oclif/config": "https://github.com/TPHRyan/oclif-config",`
3. Set missing `packageExtensions`:
```
  '@percy/cli@*':
    dependencies:
      '@oclif/command': '*'
      '@oclif/errors': '*'
```

Now this all works -- it's not optimal, and you get these warnings which won't work in strict pnp mode:
```
(node:6030) [MODULE_NOT_FOUND] Error: @oclif/config tried to access @percy/cli-config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6030) [MODULE_NOT_FOUND] Error: @oclif/config tried to access @percy/cli-exec, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6030) [MODULE_NOT_FOUND] Error: @oclif/config tried to access @percy/cli-build, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6030) [MODULE_NOT_FOUND] Error: @oclif/config tried to access @percy/cli-snapshot, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6030) [MODULE_NOT_FOUND] Error: @oclif/config tried to access @percy/cli-upload, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6030) [MODULE_NOT_FOUND] Error: @percy/cli-exec tried to access @percy/config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by JonnyPickard** [comment]
@AaronBuxbaum thanks for this workaround. I'd managed to get to step 4 on my own but didn't think to run Percy through pnpify 👍🏼
