### ISSUE TITLE
Provide a Docker image with CLI installed

### ISSUE THREAD

**Issue by mitar** [percy/cli#328]
There is an old Docker image for [Percy Agent](https://hub.docker.com/r/percyio/agent), but I could not find any for CLI. It would be great to have one slim Docker image to use.

**Comment by Robdel12** [comment]
Hey @mitar! This isn't likely something we'll do -- that docker image was never updated. All we did in it was globally install agent: https://github.com/percy/percy-agent/blob/master/Dockerfile#L2-L3 

It's always going to be better to use your CI providers docker images or a custom one you setup (if needed).

**Comment by mitar** [comment]
I made a [docker image](https://gitlab.com/mitar/mitarpage/-/blob/main/percy.dockerfile) (`registry.gitlab.com/mitar/mitarpage/percy/hash:27c5359f564bf64e6bed2973e348bc99c9e8176cb0f3fedb9ab600d9ea5dccdc`).
