### ISSUE TITLE
Add a flag to remove any iframes before making a screenshot

### ISSUE THREAD

**Issue by mitar** [percy/cli#343]
This is a followup to https://github.com/percy/cli/issues/329.

**Comment by Robdel12** [comment]
Hey @mitar! As mentioned in #329 [the recommended way would be to add an `execute` function](https://github.com/percy/cli/issues/329#issuecomment-842677068) which removes the problematic iframe.

**Comment by mitar** [comment]
That defeats the purpose of a friendly CLI tool. :-(

**Comment by Robdel12** [comment]
Hm, this would likely snowball into a ton of various flags to remove various DOM nodes. It's better to manipulate the DOM for your specific app/usecase rather than trying to pile in a bunch of flags that would do the same. We'd likely never cover the bases that way

**Comment by mitar** [comment]
Sure. One option where you can provide a CSS selector or selectors. Not too tricky?
