### ISSUE TITLE
Handle failed builds

### ISSUE THREAD

**Issue by wwilsman** [percy/cli#344]
Since snapshots begin processing as soon as the API receives them, a build can fail before all snapshots have finished uploading. In this case, a 422 error is returned from the API. We should catch these errors and stop further snapshot handling

**Comment by mitar** [comment]
Is there a way to obtain/print out the information why the build failed on the CLI side, too?

**Comment by wwilsman** [comment]
Unfortunately not. There are a myriad of reasons a snapshot could fail and we don't capture them; only that we couldn't successfully render the page. It takes somebody in support to look through internal rendering logs and find something that might give us a hint as to why it failed. It could be that it's due to external requests taking a long time to load causing our rendering environment to time out while waiting, or even something else on the page causing the browser to hang or crash.

**Comment by wwilsman** [comment]
Handled for SDKs that utilize sdk-utils with #369
