### ISSUE TITLE
Multiple ignore globs

### ISSUE THREAD

**Issue by mitar** [percy/cli#360]
[Documentation](https://docs.percy.io/docs/cli-configuration) currently says:

> ignore: Glob or comma-separated string of globs for matching the files and directories to ignore.

But I could not get multiple globs to work by using comma between them. Are you sure this works? I could also not find anything in the code to make this work. I think it should be a string or an array of strings, but not comma-separated string.

**Comment by wwilsman** [comment]
Thanks for pointing out this doc mistake @mitar! You are correct that it should be a single glob or an array of globs. Docs are updated now. 👍

**Comment by mitar** [comment]
One other thing I learned BTW, is that glob cannot start with `/` to mean the beginning of the path relative to the current working directory.
