### ISSUE TITLE
Percy builds pass even when percySnapshot() fails

### ISSUE THREAD

**Issue by MarosPistej** [percy/cli#368]
# BUG
## About
We encountered issue which was even worse as it was on auto-approve branch `master`. One `cy.percySnapshot()` command failed (unknown reason, and it happen only once) but we were surprised that cypress test pass without issue, we expected that there is some assertion that cy.percySnapshot() was successful but it looks like there isn't? Result was that there was missing snapshot which was auto-approved, so in next tests we got diff that we have new snapshot even we didn't add any.

![image](https://user-images.githubusercontent.com/43110161/120996358-896b7c80-c786-11eb-9d92-fd033d8c2292.png)

**Comment by Robdel12** [comment]
Hey @MarosPistej! This is how the SDKs currently work on purpose. We're going to be adding a flag to the CLI for users to `exit 1` if any build or snapshot errors occur in the near future.
