### ISSUE TITLE
Percy specific css not applied in v1.0.0-beta.53

### ISSUE THREAD

**Issue by vdineva** [percy/cli#386]
While trying to upgrade to v1.0.0-beta.53 of @percy/cli I noticed in your snapshots that the Percy specific css we have defined in the .percyrc file no longer gets applied

**Comment by Robdel12** [comment]
Hey @vdineva! Can you provide debug logs (`--verbose`) or a snapshot/build for us to look at? Sounds not good but not sure what's going on yet :)

**Comment by khitrenovich** [comment]
@Robdel12  You can check builds 11094543 or 11094943, for example.

**Comment by wwilsman** [comment]
Should be fixed with #387 and `beta.54`
