### ISSUE TITLE
`execute()` doesn't work in `additionalSnapshots`

### ISSUE THREAD

**Issue by chris-dura** [percy/cli#392]
```
"@percy/cli": "^1.0.0-beta.55",
```

The `execute()` function seems to work when in the "parent" snapshot:
```js
// snapshots.js

module.exports = [
	{
		name: 'snapshot one',
		url: 'http://localhost:8080',
		waitForSelector: '.some-element',
		execute() {
			document.querySelector('h1').innerHTML = 'Tilting on windmills...';
		}
	}
]
```
However, trying to run the same `execute()` in an `additionalSnapshot` (like in [this pages.js example](https://github.com/percy/cli/tree/master/packages/cli-snapshot#page-options)) it does _not_ work, and the `<h1>` content stays the same :/

```js
// snapshots.js

module.exports = [
	{
		name: 'snapshot one',
		url: 'http://localhost:8080',
		waitForSelector: '.some-element',
		additionalSnapshots: [
			{
				suffix: '--tilt',
				execute() {
					document.querySelector('h1').innerHTML = 'Tilting on windmills...';
				}
			}
		]
	}
]
```

**Comment by wwilsman** [comment]
Thanks for raising this @chris-dura!

Looks like we need to remove the `execute` from this line: https://github.com/percy/cli/blob/3cc36e7f47f8c37039345a45879594ac83713748/packages/core/src/percy.js#L342

PR out shortly 👍

**Comment by wwilsman** [comment]
End of the work day for us, so we'll merge and release that fix tomorrow! :+1:

**Comment by wwilsman** [comment]
Fix shipped in the latest release!
