### ISSUE TITLE
TypeError: PercyClient is not a constructor

### ISSUE THREAD

**Issue by holdenhinkle** [percy/cli#403]
I'm getting the following error:

```
const client = new PercyClient(options);
                 ^

TypeError: PercyClient is not a constructor
```

When I run:

```
const PercyClient = require('@percy/client');

function run() {
  const client = new PercyClient();
};

run();
```

Please advise. Thank you!

**Comment by Robdel12** [comment]
Hey @holdenhinkle! Curious what you're looking to use such a low level package for. 👀 

For the issue, you'll probably have to `default` on the require: 

```js
```

**Comment by holdenhinkle** [comment]
Thanks for your super fast response, Robert! That worked.

We want to monitor a couple of important pages in production.  I'm trying to use Percy in an AWS CloudWatch Canary script.

**Comment by Robdel12** [comment]
Gotcha! Are you looking to build your own SDK? `@percy/client` is pretty low level. You'll have to find, create, and manage your own builds & resources. You might be better off using `@percy/core` _or_ one of our prebuilt SDKs

**Comment by holdenhinkle** [comment]
Yes, `@percy/core` is what I wanted. Thanks. I've got it working :-)

How can I get a read access token so I can query a build?

**Comment by Robdel12** [comment]
You can get the full access token (read/write) from the link in the docs here: https://docs.percy.io/docs/cli-build#percy-buildwait

We'll soon be exposing these in a nice way in the UI. :D

**Comment by holdenhinkle** [comment]
Thanks Robert! 

I didn't see that in the docs. I reached out to support and they responded quickly with that same link.

Thanks again :-)

**Comment by Robdel12** [comment]
Awesome! Happy to hear -- I'll close this issue up 🎉
