### ISSUE TITLE
percyCSS attribute in my .percy.js config does not take affect

### ISSUE THREAD

**Issue by bennymeade** [percy/cli#404]
Using `percyCSS` attribute in my `.percy.js` config does not affect my webpage.

```
module.exports = {
  version: 2,
  snapshot: {
    percyCSS: 'iframe { display: none; } .footer__wrapper, .c-news-feed, .page-share { content-visibility: visible !important; }'
  },
  discovery: {
    disableCache: true,
    requestHeaders: {
      Authorization: process.env.CYPRESS_BASIC_AUTH
    }
  }
}

```

As a workaround I have to inject the css style with my Cypress test.
Am I using the attribute correctly in the above code example?

**Comment by Robdel12** [comment]
Hey @bennymeade! This usually means the CSS isn't specific enough. Do you have a build or snapshot ID I can look at?

**Comment by bennymeade** [comment]
@Robdel12 Sure, I can give you these details in a private message. How do we message directly?

**Comment by Robdel12** [comment]
Hey @bennymeade! I'm just getting back to work full time after a vacation. If you paste the build or snapshot ID here I can look. Or you can email Percy support (`support@percy.io`) -- but then I won't be helping/handling it.
