### ISSUE TITLE
Yarn 2 Dependencies. 

### ISSUE THREAD

**Issue by JonnyPickard** [percy/cli#409]
Hi guys & gals,

Sorry if this has already been brought up but I couldn't find it in the existing issues.

We use yarn 2 w/ workspaces for our monorepo setup. 

The issue i'm having is that `@percy/cli` lists all it's dependencies as `devDependencies` instead of `dependencies`. 

Yarn 2 won't install `devDependencies` so I end up with this:
(When trying to run: `yarn percy storybook ./storybook-static --widths=320,768,1024`)

![image](https://user-images.githubusercontent.com/16156445/125295994-bc70d500-e31d-11eb-94b4-b8cf4d2348f8.png)

I feel like if the package uses these dependencies they should probably be normal `dependencies` and not `devDependencies`? 

I couldn't find anything in the docs to help with this issue. However, just doing this for example: `build-storybook && npx -p @percy/cli@latest -p @percy/storybook@next -p @storybook/router -c 'percy storybook ./storybook-static' --widths=320,768,1024` (using npx) works fine.

**Comment by wwilsman** [comment]
The referenced dependencies are transitive dependencies of the `@percy/cli` package. Unfortunately, we don't support Yarn 2 (#295) and rely on a typical node dependency tree (with `node_modules`).

**Comment by JonnyPickard** [comment]
Ah ok, thanks for linking that issue!

**Comment by JonnyPickard** [comment]
Hey @wwilsman just thinking. Would it be worth having that quite clearly in the README. As it seems like people will try it to no avail? I probably spent a day trying to get it working.
