### ISSUE TITLE
--verbose is not being recognised

### ISSUE THREAD

**Issue by bennymeade** [percy/cli#411]
My run command ```npx percy exec --verbose -- cypress run --spec 'cypress/integration/site-monitoring/visual-comparison.spec.ts'```

Does not log anything:
```
  Running:  site-monitoring/visual-comparison.spec.ts                                       (1 of 1)

  Visual Comparison
[percy] Snapshot taken: https://www.company.com/page1/
    ✓ Visual comparison of pages within URL path: https://www.company.com/page1/ (10667ms)
[percy] Snapshot taken: https://www.company.com/page2/
    ✓ Visual comparison of pages within URL path: https://www.company.com/page2/ (6469ms)


  2 passing (20s)
```
My devDependencies:
```
"@percy/cli": "1.0.0-beta.58",
"@percy/cypress": "3.1.0",
```

And i've deleted my node_modules and reinstalled all packages.

I also have a config file `.percy.js`:

```
module.exports = {
  version: 2,
  discovery: {
    disableCache: false,
    requestHeaders: {
      Authorization: process.env.CYPRESS_BASIC_AUTH
    }
  }
}
```

What could be the cause?

**Comment by wwilsman** [comment]
Hey @bennymeade!

Tough to say why the flag wouldn't be working. Sometimes flags can be lost and usurped by the parent command. In this case, perhaps `npx` thinks the `--verbose` flag is for itself? Yarn goes so far as to remove the `--`, which can also sometime cause problems. 

Try this, which should pass the args down to the right commands:

```
npx percy -- exec --verbose -- cypress run --spec 'cypress/integration/site-monitoring/visual-comparison.spec.ts'
```

Notice the extra `--` after `npx percy`. This should signal to npx that all args to the right of the `--` are intended for the `percy` binary, and not npx itself. The following `--` signals to percy where your test command starts.

If the flag still doesn't work for whatever reason, you can also enable debug logs using environment variables. Setting the env var, `PERCY_LOGLEVEL=debug`, is equivalent to the `--verbose` flag.

**Comment by bennymeade** [comment]
Thanks @wwilsman  Adding the `--` before `exec` didn't resolve it for me. I got error
```
$ npx percy -- exec --verbose -- cypress run --spec 'cypress/integration/site-monitoring/visual-comparison.spec.ts'
 ›   Error: command -- not found
```

But setting ```PERCY_LOGLEVEL=debug``` as an env var did give me verbose logging so that's a really useful option. I hadn't seen that in the documentation.
