### ISSUE TITLE
percy is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nirav1516** [percy/cli#414]
I am exploring percy for our organization's visual testing. But I am not able to use percy cli even after installing it.
I installed percy as per given command in your documentation: npm install --save-dev @percy/cli 

It creates a local node_modules folder under which I can see a @percy folder. But when I try to execute percy command: percy exec -- [my command], it says the command is not recognized. I attaching a screenshot for your reference. Do I need to set any path in environment variable. Could you please help asap? 
![percyError](https://user-images.githubusercontent.com/7418486/125694405-f7190f9a-f052-4c3b-a084-5be5a6746c8e.PNG)

**Comment by wwilsman** [comment]
Hey @nirav1516!

The installed binary (or a link to it) can be found inside `node_modules/.bin`. You can reference that binary directly, or add that directory to your local path. Apologies for the confusing Java docs, most of our docs are written with the (sometimes incorrect) assumption that everybody is familiar with NPM.

I've updated the docs to reference `npx` in the command examples for now. Using `npx` will take care of Node paths: 

```
$ npx percy exec -- mvn exec:java ...
```

In the future, we plan on distributing the CLI via other package managers so it is much more friendly to use outside of the Node ecosystem.

**Comment by nirav1516** [comment]
Hi Wilsman,

Thanks for your response. Actually, I was able to do the same before you responded. Apologies for forgetting to update the thread. I now need help with something else. Would open a separate issue for the same. Appreciate your help in making the tool work.

**Comment by nirav1516** [comment]
Have opened another issue if someone can help with that: https://github.com/percy/cli/issues/415
