### ISSUE TITLE
Production website and Percy snapshots show with No CSS

### ISSUE THREAD

**Issue by bennymeade** [percy/cli#421]
I'm having a major issue with running my snapshots on production websites, so authentication cannot be an issue.

When my Cypress / Percy test starts taking screenshots the 1st image taken/uploaded is displayed and formatted correctly with all CSS styles showing. But all snapshots taken/uploaded after that do Not contain CSS styles.

I'm not seeing anything obvious in the verbose logging. What can be the cause of this?

I created a mini repo here to reproduce the issue: https://github.com/bennymeade/cypress-with-percy

![image](https://user-images.githubusercontent.com/1033474/125852648-76d67263-ebc4-4dc1-935a-298fff5de88f.png)

**Comment by Robdel12** [comment]
Hey @bennymeade! Looking through some logs, it looks like the CSS files aren't discovered. When you look at the `--verbose` logs, do you see the CSS files being logged out? If not, you'll want to increase the `network-idle-timeout` to something like 250ms. https://docs.percy.io/docs/cli-configuration#discovery

Also, any reason you have JS enabled? That typically causes more issues than it causes. If it's to work around the lazy loading images on the page, you'll want to scroll the page before calling `percySnapshot`: https://docs.percy.io/docs/capturing-lazy-loading-images

**Comment by bennymeade** [comment]
Hi @Robdel12 I added a `.percy.js` file and included a generous `networkIdleTimeout: 1000` but unfortunately the issue still occurs (I've updated my example repo linked above).

```
module.exports = {
    version: 2,
    discovery: {
      networkIdleTimeout: 1000
    }
}
```

I only enabled JS in this mini repo to see if that would help. I don't use it in my main project code. I also have dedicated working code to handle the image lazy loading, which all works.

Do you have any other suggestions for the No CSS issue? As it's killing us for production releases.

**Comment by bennymeade** [comment]
This turns out to be a config issue in our environment. When basic auth was removed from production env is cause the Percy no CSS issue.

**Comment by glambert** [comment]
Hey folks, I have a similar issue with CSS-in-JS-powered styling through https://stitches.dev/. Styles are not being applied in the Percy snapshots. I looked around the repository and documentation and couldn't find anything on the subject. For the record, I'm running tests with https://github.com/percy/percy-cypress.

Worth creating a separate issue?
