### ISSUE TITLE
Create proper assets from serialized canvas elements

### ISSUE THREAD

**Issue by Robdel12** [percy/cli#425]
## Problem

If there are a large number of canvas elements on a page, the DOM clone can become too large of an asset to upload to the API. This is because the serialized canvas elements are put into the DOM clone as base64 encoded PNGs. 

## Possible solve

In order to avoid this, we should create proper assets from the serialized canvas elements and write them to disk. Then create an asset for Percy and upload it to the API.

**Comment by TimothyLks** [comment]
About the solution to the problem, how can it be done?
Also, are there any other solutions?
