### ISSUE TITLE
Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static

### ISSUE THREAD

**Issue by nicobatalla** [percy/cli#429]
**Possible bug introduced in beta 59?**

Renovate bot is trying to update to `@percy/cli to v1.0.0-beta.59 ` and our action that runs E2E tests and take screenshots is now falling with the following error:

```
(node:1969) Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static
module: @oclif/config@1.17.0
task: runHook init
plugin: @percy/cli
root: /home/runner/work/montevideo/montevideo/node_modules/@percy/cli
```

The same action was running properly on beta.58

Our script just runs: `percy exec -- cypress run` (and some cypress env variables are used too with the --env flag)

**Comment by atmullan** [comment]
Got the same issue with nightly Cypress E2E tests, Tests are now not executing due the Percy CLI crashing with the error

`percy exec -t 350 -- node scripts/cypress-ci.js "staging" "***" "***" "***" "***" "***" "***" "0" "***"
--
255 |  
256 | (node:351) Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static
257 | module: @oclif/config@1.17.0
258 | task: runHook init
259 | plugin: @percy/cli
260 | root: /codebuild/output/src235357999/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/cloudranger-v2-testing/Cypress/node_modules/@percy/cli
261 | See more details with DEBUG=*
262 | Error: can't resolve reference /snapshot#/properties/name from id
263 | /config/static
264 | npm ERR! code ELIFECYCLE
265 | npm ERR! errno 1
266 | npm ERR! cloudranger-v2-cypress@1.0.0 cypress:runCI: `percy exec -t 350 -- node scripts/cypress-ci.js "staging" "***" "***" "***" "***" "***" "***" "0" "***"`
267 | npm ERR! Exit status 1`

**Comment by kostasmackevicius** [comment]
Getting the same error. Please react quickly.

**Comment by andyasberry** [comment]
Getting a similar error - started yesterday evening. Wasn't seeing this issue with v1.0.0-beta.58

**Comment by oshi97** [comment]
seeing the same issue just trying to follow the instructions at https://docs.percy.io/docs/puppeteer
downgrading to beta.58 (also arbitrarily tried beta.57 and beta.40) doesn't seem to fix the issue

**Comment by Robdel12** [comment]
We're working on a fix 👍🏼 Sorry about that!

**Comment by andyasberry** [comment]
@Robdel12 thanks so much!!!

**Comment by kostasmackevicius** [comment]
Still getting error:
`(node:22006) Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static
module: @oclif/config@1.17.0`

The command how we run the tests is:
```
sh 'npm install --save-dev @percy/cli'
sh "LOG_LEVEL=debug npx percy exec -- mvn clean install ...
```

**Comment by Robdel12** [comment]
@kostasmackevicius can you confirm you're not on `beta.59`? `npx percy --version` should show the version.

**Comment by kostasmackevicius** [comment]
@Robdel12 Seems we are using 52 beta version. Here is screenshot.
<img width="421" alt="Screen Shot 2021-07-23 at 16 12 31" src="https://user-images.githubusercontent.com/60097844/126786772-d4e71dc5-33db-481f-935f-434e0e45f3f5.png">

Question: How to update it. 
Thanks in advance.

**Comment by oshi97** [comment]
https://www.google.com/search?q=how+to+install+specific+npm+package+version

**Comment by kostasmackevicius** [comment]
Thanks Gentlemens. Issue solved.
