### ISSUE TITLE
Add `repository` field to package.json

### ISSUE THREAD

**Issue by ybiquitous** [percy/cli#435]
Hi, thank you for providing the nice package!

One question. I’m wondering why the packages included in this repository don’t have the [`repository`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository) field in its `package.json` file. 🤔 

There are the following advantages of the `repository` field:

- A link to the repository is added on [npmjs.com](https://www.npmjs.com/package/@percy/cli)
- The [`npm repo`](https://docs.npmjs.com/cli/v7/commands/npm-repo) command works, such as `npm repo @percy/cli`
- Dependabot’s pull requests have useful links to the repository, such as releases or changelog

I would be very happy if you could add it. Thank you.

**Comment by Robdel12** [comment]
Hey @ybiquitous! No particular reason why we're not -- just haven't added it to any of the packages `package.json`s. Totally open or PRs :)
