### ISSUE TITLE
cy.percySnapshot sends only 1st snapshot

### ISSUE THREAD

**Issue by MartinPtrl** [percy/cli#451]
## The problem

We are updating version of @percy/cli from 1.0.0-beta.48 to 1.0.0-beta.60 and we are observing regression in one of our tests. This test was sending 4 snapshots to percy.io but now is sending only the 1st one and then it times out.

## Environment

Percy/v1
@percy/client/1.0.0-beta.60
@percy/cypress/3.1.0 (cypress/7.7.0; node/v14.17.3; circle)

I guess you can take the snapshot id from this url, I'm just masking some identifiers related to our project
https://percy.io/042e5367/<our_project>/builds/11804432/unchanged/664231073

## Error message in build

Error: Command failed with exit code 1: percy exec -- cypress run --browser chrome --record false
    at makeError (/home/circleci/repo/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/circleci/repo/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  command: 'percy exec -- cypress run --browser chrome --record false',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.

**Comment by Robdel12** [comment]
Hey @MartinPtrl! Could you share the Percy logs from that test run? Looks like there was a single snapshot captured, so I'd expect there to be logs.

**Comment by Robdel12** [comment]
Oh, this also might be related to #453 -- can you try beta.61 too?

**Comment by MartinPtrl** [comment]
ok, beta.61 actually helped us 👍

**Comment by MartinPtrl** [comment]
thanks for looking into this @Robdel12 much appreciated 🙇‍♂️
