### ISSUE TITLE
Create meta actions for updating SDK repos

### ISSUE THREAD

**Issue by wwilsman** [percy/cli#462]
Thanks to #457, it was brought to our attention that our dependent GitHub Actions can be automatically updated. Only one was out-of-date and it isn't critical that it is up-to-date, but this raised the issue that changes like enabling action auto-updates need to ripple throughout the SDK ecosystem.

We've already faced this issue several times, most recently this week while updating labels across all SDK repos. Rather than spend most of or half of a day creating small copy-paste PRs, we can spend a day or two to automate it. The catch will be that actions from this repo will need read/write access to other repos (likely via a bot account). Some repos also have special needs, so we might not be able to wholesale replace actions entirely, and also might need to create an action template system.

**Comment by Robdel12** [comment]
Want to note that we'll need to add a specific label config (so we don't get language labels created on all the repos)
