### ISSUE TITLE
1.0.0-beta.63 outputs timeout errors

### ISSUE THREAD

**Issue by agrobbin** [percy/cli#478]
## The problem

Since upgrading to Beta 63 this morning, we have started seeing significant degradation in Percy snapshot retrieval:

```
[percy] Encountered an error taking snapshot: [snapshot name redacted]
[percy] Error: Navigation failed: Timeout of 30000ms exceeded.
```

Weirdly the builds in the Percy UI itself seem to be OK, but test run times have skyrocketed due to these timeouts.

## Environment

- Node version: 14.17.3
- `@percy/cli` version: 1.0.0-beta.63
- Version of Percy SDK you’re using: percy-capybara 5.0.0
- OS version: Ubuntu 20.04.2
- Type of shell command-line [interface]: `yarn percy exec -- bundle exec rake`

**Comment by Robdel12** [comment]
Hey @agrobbin! In order to debug this kind of issue we'll need more (and preferably unedited) logs. This usually means there's something hanging in asset discovery for that snapshot

**Comment by agrobbin** [comment]
Happy to provide it! What kind of logs am I looking for? A Percy log that's stored on a CI node while snapshots are retrieved? a Percy build number?

My hunch is that this is somehow related to #469, though I don't know specifically *why* it would've caused this problem suddenly.

**Comment by Robdel12** [comment]
Whoops, I quickly typed a reply before a series of meetings 😅 If you want to attach it to an email, you can send it to robert (at) percy.io.

You can get the verbose logs by adding `--verbose` (I see you're using yarn, so it'd be `yarn percy exec --verbose -- -- bundle exec`). Or setting the env var `PERCY_LOGLEVEL=debug`

**Comment by Robdel12** [comment]
Thanks for the email -- I did get the logs. We dug in and started working on a fix Friday. We'll have a fix out this week (the next day or so 🤞🏼) Basically, when we capture the DOM, we serialize iframes (if possible). When we take that serialized DOM and run asset discovery over it, it hangs because the of iframe CORS requests (we get one response and the rest are forever inflight). That's the gist of it, at least :p 

Anyways, this should be fixed by mid-week. Super big thanks for the logs! That was really helpful for us to crack this one open 😃

**Comment by agrobbin** [comment]
Happy to have been able to help @Robdel12! Let me know if there's anything else I can do. Once a fix is out I will do my best to test it quickly.

**Comment by Robdel12** [comment]
This _should_ be fixed in `1.0.0-beta.64` (https://github.com/percy/cli/releases/tag/v1.0.0-beta.64). Curious to hear how it works out 👀  The linked PR has a pretty extensive description for the various fixes, if you're curious.

**Comment by agrobbin** [comment]
@Robdel12 seems like things are working as expected on beta 64! Thanks so much for the quick resolution here.

**Comment by khitrenovich** [comment]
@Robdel12 We upgraded immediately, and last 14 runs look fine for us too. Thank you for the quick fix!
