### ISSUE TITLE
Percy CLI Snapshot should wait for network to be idle between resizes

### ISSUE THREAD

**Issue by cancan101** [percy/cli#511]
Reposting the issue from https://github.com/percy/cli/discussions/510#discussioncomment-1208299 (/CC @Robdel12)

when the percy cli iterates over the widths:
https://github.com/percy/cli/blob/feecfde20f8eb0dbc5f645771e0549f58185cb1a/packages/core/src/percy.js#L327-L330
it will cause the browser to at first request a different image from the sourceset / based on CSS but then cancel that request when the image is no longer needed. You may need to make a `await this.network.idle()` call between sizes.

**Comment by Robdel12** [comment]
Thanks for this! We have one more PR behind this bug fix and then the fix will be released 👍🏼

**Comment by cancan101** [comment]
Wow you got this fixed so fast that I didn't even have time to post my second bug / feature request which is the ability to run JS (execute) on a per width basis. Right now I need to scroll to the bottom of the page for each width otherwise we only load lazily loaded images for whatever the last width is.

**Comment by cancan101** [comment]
Okay, posted to: https://github.com/percy/cli/issues/513

**Comment by TwinbrotherPro** [comment]
I have the same problem.

I am testing my application with two different widths representing two media breakpoints in my application. Once percy resizes the window my images are reloaded and therefore not visible in the screenshot.

For me it looks like as we need another `waitForDiscoveryNetworkIdle` after the `page.resize` [Link to Code](https://github.com/percy/cli/blob/e5e6ad8f9db6549e2a58ec33ed1604dba9a46dcf/packages/core/src/snapshot.js#L349).
