### ISSUE TITLE
Ability to Execute Javascript between Resizes on Percy CLI Snapshot

### ISSUE THREAD

**Issue by cancan101** [percy/cli#513]
It would be great to be able to run JS (`execute`) between _each_ width. Currently I am using the `execute` ability to scroll to the bottom of the page in order to trigger lazily loaded images. However since `execute` runs only _once_ after the last width is set, the only images that are loaded are those requested by the last width. Instead it would be good to be able to either declaratively scroll to the bottom or more generally run JS between width changes.

This is the JS code that I am running:
```js
function sleep(ms) {
   return new Promise(resolve => setTimeout(resolve, ms));
}
window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" });
await sleep(2000);
window.scrollTo(0,0);
await sleep(5000);
```

This comes up when using a `srcset` with any sort of lazy loading behavior. 

The current flow is:
```
set initial width
go to page
iterate over widths, ending on the last one
wait for any specified timeout
wait for any specified selector
execute any javascript
wait for network
```
This issue comes up for example on any pages using next.js' [next/image](https://nextjs.org/docs/api-reference/next/image).

**Comment by cancan101** [comment]
Alternatively, rather than running JS between _each_ width change, might be the option to run JS / scroll before iterating through the list of widths. In some cases, this would cause images to be lazily loaded such that subsequent changes to the width cause the browser to then actually fetch the image files. The success of this approach though may depend on how the lazy loading is implemented (native browser support, using JS, etc).

**Comment by wwilsman** [comment]
Hey @cancan101! I actually had the same followup idea as you when I first read this. For native lazy loading the before script could replace all `loading="lazy"` with `loading="eager"`. 

Before logging off yesterday I spiked a quick approach to this I think we're happy with. At first I was only aiming to add an option to execute JS immediately after page navigation, but with this approach it's actually nice and easy to also add an option to execute JS between page resizing.

It'll look something like this:

```js
// will accept a normal function, or now an object
execute: { 
  afterNavigation: () => {}, // runs after navigation but before resize
  afterResize: () => {},     // runs after each resize is triggered
  beforeSnapshot: () => {}   // runs before actually taking a snapshot
}
```

I just need to write some tests today for what I have to PR this. Then after writing some tests for an unrelated feature, we'll cut a new release later today. 👍

**Comment by patricknelson** [comment]
Is this not documented (or possible) for the YAML config? The documentation is pretty confusing since it shows YAML in one spot, but then these extra options are only in JSON format. 

https://docs.percy.io/docs/percy-snapshot

**Comment by patricknelson** [comment]
p.s. The reason why I'm confused is because I'm trying this in `additionalSnapshots` which itself isn't really well documented, at least not in an obvious spot (partly why it's so confusing)
