### ISSUE TITLE
Command Line Support for Downloading Chromium

### ISSUE THREAD

**Issue by cancan101** [percy/cli#558]
repost from https://github.com/percy/cli/discussions/554#discussioncomment-1343820:

Add a way to tell tell Percy-cli to _just_ download chromium (e.g. something like `npx percy snapshot --chromium-only`).

That way the testing can be broken up from setting up the environment for any number of reasons:
- caching
- setting preloads / environmental variables that apply just to the testing step

**Comment by wwilsman** [comment]
Hey @cancan101!

Regarding caching and env setup, you can use the environment variable `PERCY_POSTINSTALL_BROWSER=true` when installing your dependencies. https://docs.percy.io/docs/caching-asset-discovery-browser-in-ci

If you need to install the browser separately of the install process for whatever reason, you can do something like this after installing the CLI: `node --require @percy/core/post-install`
