### ISSUE TITLE
packages/cli uses `@oclif/command` but does not declare in it's dependencies

### ISSUE THREAD

**Issue by csi-lk** [percy/cli#635]
## The problem

looks like it's being used here:
https://github.com/percy/cli/blob/master/packages/cli/index.js#L69

seems that it's relying on package hoisting which causes issues with yarn v3

## Environment

- yarn v3.1.1

## Debug logs

```
Error: @percy/cli tried to access @oclif/command, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @oclif/command (via "@oclif/command/flush")
Required by: @percy/cli@npm:1.0.0-beta.70 (via ~/dev/csi.lk/.yarn/cache/@percy-cli-npm-1.0.0-beta.70-47d784f1db-64b983337f.zip/node_modules/@percy/cli/bin/)
```

## Code to reproduce issue

Create new repo using yarn v3
Install percy cli
Run percy cli
See issue

Edit: looks like `@oclif/errors` is missing too

**Comment by wwilsman** [comment]
Fixed with #670
