### ISSUE TITLE
Handle incorrect browser-supplied mime type

### ISSUE THREAD

**Issue by wwilsman** [percy/cli#790]
Misconfigured servers may sometimes forget to include a `Content-Type` header, which is where a response's mime type is inferred from. It appears, however, that while the browser renders responses with missing content-types fine due to mime type sniffing, the [`response.mimeType`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response) CDP property does not convey that inferred mime type. Instead, the property defaults to `text/plain`, which is usually incorrect.

In asset discovery, we should add logic around `text/plain` response mime types that ensure there is a `Content-Type` header. If there is no header, and the response URL contains an extension, we should infer the mime type ourselves.

**Comment by Robdel12** [comment]
Fixed with #921
