### ISSUE TITLE
Cannot find module with latest percy/cli 1.0.0 install 

### ISSUE THREAD

**Issue by josh803316** [percy/cli#855]
## The problem

I'm attempting to upgrade to @percy/cli 1.0.0 (my CI logs told me a new version was available)

When I ran `npm install` I got the following

```bash
m ERR! command sh -c node ./post-install
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/josh/git/core-web/node_modules/@percy/core/post-install'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
```

## Environment

- Node version: v16.14.2
- `@percy/cli` version: Current: "@percy/cli": "^1.0.0-beta.76", attempting to upgrade to 1.0.0
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID:
- OS version:
- Type of shell command-line [interface]:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Debug logs

See above

## Code to reproduce issue

Given the nature of testing/environment bugs, it’s best to try and isolate the
issue in a reproducible repo. This will make it much easier for us to diagnose
and fix.

**Comment by wwilsman** [comment]
Closing this in favor of the other thread with more activity
