### ISSUE TITLE
Getting an error for @percy/cli-command when upgrading @percy/cli

### ISSUE THREAD

**Issue by allypalanzi** [percy/cli#978]
## The problem

When trying to upgrade my node modules, I'm getting an issue where it cannot find version `1.5.1` of `@percy/cli-command`
![Screen Shot 2022-06-30 at 3 23 14 PM](https://user-images.githubusercontent.com/1761730/176771820-56ed4dd7-3267-4061-b823-e65fe7ddc7d8.png)

I dont have this package manually installed, am only using it through @percy/cli

## Environment

- Node version: 16.14
- `@percy/cli` version: 1.5.1
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID:
- OS version:
- Type of shell command-line [interface]:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Debug logs

If you are reporting a bug, _always_ include logs! [Give the "Debugging SDKs"
document a quick read for how to gather logs](https://docs.percy.io/docs/debugging-sdks#debugging-sdks)

Please do not trim or edit these logs, often times there are hints in the full
logs that help debug what is going on.

## Code to reproduce issue

Given the nature of testing/environment bugs, it’s best to try and isolate the
issue in a reproducible repo. This will make it much easier for us to diagnose
and fix.

**Comment by Robdel12** [comment]
Hey @allypalanzi! I think there's something weird going on with NPM. The release workflow shows all the packages were released without any issues: https://github.com/percy/cli/runs/7138220134?check_suite_focus=true#step:6:249

NPM on the package list shows 1.5.1, but clicking it goes to 1.5.0 [and also errors on 1.5.1](https://www.npmjs.com/package/@percy/cli-command/v/1.5.1). So something is really funky 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/2072894/176777357-da62c7a8-aa4d-4475-b512-ca703f5af6a4.png">


I think I'm going to wait to see if there's anything that needs to propagate before trying to republish/release another version.

**Comment by allypalanzi** [comment]
thanks all, i'll close this. i had checked the NPM status page but it didnt have anything there yet!

**Comment by Robdel12** [comment]
We're on the cutting edge! 😅 For record keeping, this is the status page for it: https://status.npmjs.org/incidents/6wr25yb0b2dd

Once that's resolved I'll double back to make sure we don't have rerelease or anything. Thanks for the report!

**Comment by Robdel12** [comment]
👋🏼 It appears this has been back filled and resolved by NPM (I'm able to upgrade to the latest in my reproduction projects)
